<div style="text-align: center; font-family: Arial, sans-serif; margin-top: 50px;">
<h1 style="font-size: 36px; font-weight: bold; color: #4CAF50;">Mini-projet 1 - Méthode Monte Carlo</h1>
<h2 style="font-size: 20px; font-weight: bold; color: #4CAF50;">PHS3903</h2>
<h2 style="font-size: 20px; margin-bottom: 20px;"> Marie-Lou Dessureault, </h2>
<h2 style="font-size: 16px; margin-bottom: 10px;">2211129, </h2>
<h2 style="font-size: 16px; margin-bottom: 10px;">22 janvier 2024</h2>
<h2 style="font-size: 16px; margin-bottom: 10px;">Shawn Molesky, Maksim Skorobogatiy, Jérémie Villeneuve</h2>
</div>


### Calcul du volume d'une $N$-sphère (20 points)

### Introduction
Une $N$-sphère de rayon $R$ est définie comme l'ensemble des points situés à une distance inférieure ou égale à $R$ de l'origine dans un espace à $N$ dimensions. Si on utilise les coordonnées cartésiennes $(x_1, x_2, \dots, x_N)$ pour décrire un point, alors ce point est situé à l'intérieur de la $N$-sphère si le critère suivant est respecté :

$$
\sum_{i=1}^{N} x_i^2 \leq R^2, \quad N=1,2,\dots
$$

Voici quelques exemples de $N$-sphères afin de clarifier ce concept :
* Une 3-sphère est la sphère habituelle en trois dimensions. Son volume est la boule dont la sphère est le contour.
* Une 2-sphère est un cercle. Son volume est l'aire du disque circonscrit par le cercle.
* Une 1-sphère est formée de deux points sur une droite qui sont situés à égale distance de l'origine. Son volume est défini comme la longueur du segment.

Ce concept peut sembler abstrait, mais il apparaît naturellement en physique statistique quand on travaille dans l'espace de phase pour étudier les propriétés d'un ensemble de $N$ particules avec une énergie fixe (ex. : gaz idéal dans une boîte fermée). 

Dans ce mini-devoir, on vous demande de calculer le volume d'une $N$-sphère de rayon unitaire $R=1$ à l'aide de la méthode de Monte-Carlo vue en classe pour le calcul d'intégrales. Le résultat est déjà connu, à savoir :

$$
V_N = \frac{\pi^{N/2}}{\Gamma\left(\frac{N}{2} + 1\right)},
$$
où $\Gamma(x)$ est la fonction gamma, ce qui vous permettra de calculer l'erreur afin d'analyser le comportement de l'algorithme.

### Choix de la méthode de Monte-Carlo

**a) [4 pts]** Expliquer pourquoi les méthodes de Monte Carlo pour l'intégration sont avantageuses pour le calcul d'intégrales à $N$ dimensions lorsque $N$ devient grand.

### Réponse a):
*(Ajoutez votre réponse ici)*

### Calcul du volume

**b) [6 pts]** Calculer le volume d'une $N$-sphère de rayon unitaire pour $N = \left\{3,6\right\}$. Pour chacune de ces $N$-sphères, calculer le résultat en faisant varier le nombre de points générés à chaque essai en utilisant les valeurs $N_{tot} = \left\{100,200,400,800,1600\right\}$. Générer 100 essais par simulation et utiliser la valeur moyenne du volume comme résultat. On vous demande donc de calculer dix valeurs de volume (cinq par $N$-sphère).

Présenter vos résultats sous forme de tableau, en fournissant une incertitude relative sur chaque résultat. Expliquer comment cette incertitude a été calculée.

### Réponse b):
Pour calculer le volume d'une $N$-sphère, le code ci-dessous a été utilisé. Les résultats obtenus pour les valeurs de $N$ et $N_{tot}$ demandées sont présentés dans le tableau 1 ci-dessous. L'incertitude de chaque résultat a été obtenue à partir de l'écart-type des 100 essais:
$$
\sigma =  \sqrt{\frac{1}{N} \sum_{i=1}^{N} (x_i - \mu)^2},
$$
où $N=100$ dans le cas ci-présent, et $\mu$ est la moyenne des 100 essais. Pour obtenir l'incertitude relative, l'incertitude $\sigma$ est divisée par la moyenne $\mu$ des essais:
$$
\sigma_{rel} = \frac{\sigma}{\mu}\cdot 100.
$$
La multiplication par 100 sert à ramener l'incertitude relative en terme de pourcentage.
<table border="1" width="75%" align="center">
    <caption>Tableau 1: Volume d'une N-sphère pour N={3,6} et pour certains N<sub>tot</sub></caption>
    <tr>
        <th>N</th>
        <th colspan="5">3</th>
        <th colspan="5">6</th>
    </tr>
    <tr>
        <td>N<sub>tot</sub></td>
        <td>100</td>
        <td>200</td>
        <td>400</td>
        <td>800</td>
        <td>1600</td>
        <td>100</td>
        <td>200</td>
        <td>400</td>
        <td>800</td>
        <td>1600</td>
    </tr>
    <tr>
        <td>Volume</td>
        <td>4.23 &plusmn; 8% </td>
        <td>4.22 &plusmn; 6%</td>
        <td>4.19 &plusmn; 4%</td>
        <td>4.18 &plusmn; 3%</td>
        <td>4.18 &plusmn; 2%</td>
        <td>5.29 &plusmn; 37%</td>
        <td>5.25 &plusmn; 23%</td>
        <td>5.38 &plusmn; 16%</td>
        <td>5.06 &plusmn; 11%</td>
        <td>5.12 &plusmn; 9%</td>
    </tr>
</table>


In [ ]:
import numpy as np
import math

# Paramètres géométriques
R = 1.0 # Rayon de la sphère (m)

# Paramètres généraux de simulation
D_val = [3,6]  # Nombre de dimensions
Ntot_val = 100 * 2 ** (np.arange(0, 5, 1))  # Nombre de points par essai
Ness = 100 # Nombre d'essais par simulation

a = 1  # Dimension de la boîte cubique dans laquelle les points aléatoires seront générés

# Boucle sur le nombre de simulations
ND = len(D_val)
NNtot = len(Ntot_val)

V = np.zeros((ND, NNtot))  # Volumes calculés pour chaque série d'essais
inc = np.zeros((ND, NNtot)) # Incertitudes pour chaque série d'essais

for d in range(0, ND):
    D = D_val[d]  # Dimension
    Vtot = ( a * 2 ) ** D # Volume du domaine
   
    for n in range(0, NNtot):
        Ntot = Ntot_val[n]  # Nombre de points

        Vind = np.zeros(Ness) # Volumes calculés pour chaque essai individuel

        for k in range(0, Ness): # Boucle sur les essais
            # Génération des nombres aléatoires (distribution uniforme)
            np.random.seed() # Initialise le générateur de nombres pseudo-aléatoires afin de ne pas toujours produire la même séquence à l'ouverture de Python...
            pts = a * np.random.uniform(low=-a, high=a, size=(Ntot, D)) # Coordonnées des points
            
            # Calcul du volume
            distances = np.linalg.norm(pts, axis=1)
            Nint = np.sum(distances <= R) # Nombre de points à l'intérieur
            Vind[k] = Nint / Ntot * Vtot # Volume calculé pour cet essai

        V[d, n] = np.mean(Vind) # Volume moyenné sur l'ensemble des essais
        inc[d, n] = np.std(Vind) # Incertitude sur l'ensemble des essais (écart-type)

inc_rel = inc / V * 100 # Calcul de l'incertitude relative


[[4.2312  4.2172  4.1868  4.1767  4.18205]
 [5.2928  5.248   5.3792  5.064   5.1248 ]]
[[0.34314219 0.26498332 0.1817079  0.13241643 0.09920457]
 [1.98060096 1.25658585 0.84717847 0.56619431 0.46179753]]
[[ 8.10980777  6.28339467  4.34001857  3.17036001  2.37215179]
 [37.42066504 23.94409014 15.74915359 11.18077237  9.01103519]]


### Réponse c):
*(Ajoutez votre réponse ici)*

### Analyse de l'erreur

**c) [4 pts]** À l'aide des résultats précédents obtenus, tracer un graphique de l'erreur relative $E$ sur le volume calculé en fonction de $N_{tot}$ pour chaque $N$-sphère. (Vous tracerez donc deux séries de données sur le même graphique.) Utiliser une échelle qui permet de représenter facilement le comportement de l'erreur.

In [ ]:
Vth = (np.pi ** (D / 2)) / math.gamma(D / 2 + 1) # Volume théorique

### Réponse c):
*(Ajoutez votre réponse ici)*

**d) [2 pts]** Déterminer le comportement de l'erreur relative en calculant l'exposant $p$ tel que :

$$
E = O(N_{tot}^p)
$$
pour chacune des deux $N$-sphères.

### Réponse d):
*(Ajoutez votre réponse ici)*

**e) [4 pts]** Discuter des points suivants :
* Comment les valeurs de $p$ calculées se comparent-t-elle aux valeurs théoriques attendues ?
* La précision des résultats obtenus est-elle la même pour la 3-sphère et pour la 6-sphère ?
* Comment l'incertitude relative calculée en (b) se compare-t-elle à l'erreur relative ?

### Réponse e):
*(Ajoutez votre réponse ici)*